model:
  model_path: model_assets/llama_1b5_config
  tokenizer_path: model_assets/tokenizer
  vocab_size: 151646
  foundation:
    ttt_layers: [0, 6, 12, 18]
    ttt_mode: true
    ttt_proj: true
    ttt_lr: 3
    ttt_chunk: 4096
    ttt_target: input_embed

data:
  data_dir: data
  train_path: piles_packed_32768.jsonl
  train_size: 60000000000
  dataloader_type: native
  datasets_type: iterable
  data_type: plaintext
  max_seq_len: 32768
  text_keys: content_split
  drop_last: true

train:
  output_dir: data/output/1b5_ttt
  data_parallel_mode: fsdp2
  ulysses_parallel_size: 1
  global_batch_size: 128
  micro_batch_size: 1
  rmpad: false
  use_wandb: true
  wandb_project: inplace-ttt-figure2
  wandb_name: 1b5-ttt
  max_steps: 14325
  rmpad_with_pos_ids: false
  dyn_bsz_margin: 0
  optimizer: adamw
  lr: 3.0e-4
  lr_warmup_ratio: 0.10
  lr_decay_style: cosine
  lr_decay_ratio: 0.90
  lr_min: 3.0e-6
  weight_decay: 0.1
  max_grad_norm: 1.0
  enable_mixed_precision: true
  enable_gradient_checkpointing: true
  enable_full_shard: true
  enable_fsdp_offload: false
  enable_activation_offload: false
  init_device: meta
  ckpt_manager: dcp
  save_steps: 500
  save_hf_weights: true
  empty_cache_steps: 10
  seed: 42